# copy from Tanjo-san's repository https://github.com/tom-tan/cwl-template-for-vscode/blob/main/.github/workflows/ci.yml
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup python for cwltool
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.x'
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - name: Install dependencies
      run: |
        pip install cwltool
        pip install cwltest
        pip install jupyter==1.0.0
        pip install ipykernel==6.29.4
        pip install pandas==2.2.0
        pip install pyarrow==15.0.0
        pip install numpy==1.26.3
        pip install matplotlib==3.8.2
        pip install seaborn==0.13.2
        pip install urllib3==2.1.0
        pip install retry==0.9.2
        pip install PyYAML==6.0.1
        pip install requests==2.31.0
        pip install polars==1.17.1
        pip install cwltool==3.1.20241112140730
        pip install cwltest==2.5.20240906231108
        pip install argparse==1.4.0
        pip install unipressed==1.3.0
        pip install papermill==2.6.0
        pip install pipx==1.6.0

    - uses: actions/setup-node@v4
      with:
        node-version: 'latest'
    - name: Run tests
      id: run-tests
      uses: common-workflow-lab/run-tests@v1
      with:
        test-list: test.yml
        runner: cwltool
        timeout: 40